/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

val quarkusPlatformGroupId ="io.quarkus.platform"
val quarkusPlatformArtifactId = "quarkus-bom"
val quarkusPlatformVersion = "2.12.2.Final"

plugins {
    kotlin("jvm") version "1.7.10"
    kotlin("plugin.allopen") version "1.7.10"
    kotlin("plugin.serialization") version "1.7.10"
}


repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    implementation("software.amazon.jsii:jsii-runtime:1.71.0")
    implementation("software.amazon.awscdk:core:1.11.0.DEVPREVIEW")
    implementation("software.amazon.awscdk:lambda:1.11.0.DEVPREVIEW")
    implementation("software.amazon.awscdk:dynamodb:1.11.0.DEVPREVIEW")
    implementation("software.amazon.awscdk:s3:1.11.0.DEVPREVIEW")
    implementation("software.amazon.awscdk:sns:1.11.0.DEVPREVIEW")
    implementation("com.amazonaws:aws-lambda-java-core:1.2.2")
    implementation("com.amazonaws:aws-lambda-java-events:3.11.0")
    implementation("com.amazonaws:aws-java-sdk-sts:1.12.364")
    implementation("com.amazonaws:aws-java-sdk-lambda:1.12.364")
    implementation("com.amazonaws:aws-java-sdk-dynamodb:1.12.364")
    implementation("com.amazonaws:aws-java-sdk-sns:1.12.351")
    implementation("org.apache.logging.log4j:log4j-core:2.19.0")
    implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:1.4.1")

    implementation("commons-logging:commons-logging:1.2")
    implementation("org.junit.jupiter:junit-jupiter:5.9.0")
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.8.0-RC")
    testImplementation("org.jetbrains.kotlin:kotlin-test:1.8.0-RC")


    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")
    implementation("io.quarkus:quarkus-arc")
    implementation("io.quarkus:quarkus-logging-json")

    implementation("io.quarkus:quarkus-config-yaml")
    testImplementation("io.quarkus:quarkus-junit5")

    testImplementation("io.kotest:kotest-runner-junit5:$version")
    implementation ("io.quarkus:quarkus-resteasy")
    testImplementation("io.rest-assured:rest-assured")
    implementation("io.quarkus:quarkus-kotlin")

    implementation(enforcedPlatform("${quarkusPlatformGroupId}:${quarkusPlatformArtifactId}:${quarkusPlatformVersion}"))

}

group = "com.awsblog.queueing"
version = "1.0.0"
description = "awsblog-queueing"
java.sourceCompatibility = JavaVersion.VERSION_1_8
//
//publishing {
//    publications.create<MavenPublication>("maven") {
//        from(components["java"])
//    }
//}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

allOpen {
    annotation("javax.ws.rs.Path")
    annotation("javax.enterprise.context.ApplicationScoped")
    annotation("io.quarkus.test.junit.QuarkusTest")
}

tasks.withType<org.jetbrains.kotlin.gradle.tasks.KotlinCompile> {
    kotlinOptions.jvmTarget = JavaVersion.VERSION_17.toString()
    kotlinOptions.javaParameters = true
}
